/**
 * 食物数据库种子数据
 * 包含常见食物的营养成分信息
 */

export const seedFoods = [
  // ==================== 主食类 ====================
  {
    name: '米饭',
    nameEn: 'Steamed Rice',
    category: '主食',
    calories: 116,
    protein: 2.6,
    carbs: 25.9,
    fat: 0.3,
    fiber: 0.3,
    servingSize: 100,
  },
  {
    name: '糙米饭',
    nameEn: 'Brown Rice',
    category: '主食',
    calories: 111,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    fiber: 1.8,
    servingSize: 100,
  },
  {
    name: '面条',
    nameEn: 'Noodles',
    category: '主食',
    calories: 138,
    protein: 4.5,
    carbs: 28.1,
    fat: 0.8,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '全麦面包',
    nameEn: 'Whole Wheat Bread',
    category: '主食',
    calories: 247,
    protein: 9.5,
    carbs: 46.4,
    fat: 2.8,
    fiber: 6.0,
    servingSize: 100,
  },
  {
    name: '燕麦',
    nameEn: 'Oatmeal',
    category: '主食',
    calories: 367,
    protein: 13.2,
    carbs: 66.3,
    fat: 6.7,
    fiber: 10.3,
    servingSize: 100,
  },
  {
    name: '红薯',
    nameEn: 'Sweet Potato',
    category: '主食',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 2.5,
    servingSize: 100,
  },
  {
    name: '土豆',
    nameEn: 'Potato',
    category: '主食',
    calories: 77,
    protein: 2.0,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    servingSize: 100,
  },
  {
    name: '馒头',
    nameEn: 'Steamed Bun',
    category: '主食',
    calories: 223,
    protein: 7.0,
    carbs: 47.0,
    fat: 1.1,
    fiber: 1.3,
    servingSize: 100,
  },
  {
    name: '包子（肉馅）',
    nameEn: 'Meat Bun',
    category: '主食',
    calories: 227,
    protein: 6.4,
    carbs: 33.5,
    fat: 7.8,
    fiber: 0.8,
    servingSize: 100,
  },
  {
    name: '饺子（猪肉白菜）',
    nameEn: 'Pork Cabbage Dumpling',
    category: '主食',
    calories: 198,
    protein: 7.1,
    carbs: 26.5,
    fat: 6.8,
    fiber: 0.9,
    servingSize: 100,
  },
  {
    name: '小米粥',
    nameEn: 'Millet Porridge',
    category: '主食',
    calories: 46,
    protein: 1.4,
    carbs: 9.7,
    fat: 0.3,
    fiber: 0.4,
    servingSize: 100,
  },
  {
    name: '白粥',
    nameEn: 'Rice Porridge',
    category: '主食',
    calories: 30,
    protein: 0.7,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.1,
    servingSize: 100,
  },
  {
    name: '炒饭',
    nameEn: 'Fried Rice',
    category: '主食',
    calories: 188,
    protein: 4.5,
    carbs: 28.5,
    fat: 6.2,
    fiber: 0.8,
    servingSize: 100,
  },
  {
    name: '炒面',
    nameEn: 'Fried Noodles',
    category: '主食',
    calories: 163,
    protein: 4.8,
    carbs: 24.5,
    fat: 5.3,
    fiber: 1.1,
    servingSize: 100,
  },
  {
    name: '紫薯',
    nameEn: 'Purple Sweet Potato',
    category: '主食',
    calories: 82,
    protein: 1.5,
    carbs: 19.5,
    fat: 0.2,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '玉米',
    nameEn: 'Corn',
    category: '主食',
    calories: 112,
    protein: 4.0,
    carbs: 22.8,
    fat: 1.2,
    fiber: 2.9,
    servingSize: 100,
  },

  // ==================== 肉类 ====================
  {
    name: '鸡胸肉',
    nameEn: 'Chicken Breast',
    category: '肉类',
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鸡腿肉',
    nameEn: 'Chicken Thigh',
    category: '肉类',
    calories: 209,
    protein: 26.0,
    carbs: 0,
    fat: 11.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '牛肉',
    nameEn: 'Beef',
    category: '肉类',
    calories: 250,
    protein: 26.0,
    carbs: 0,
    fat: 15.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '瘦牛肉',
    nameEn: 'Lean Beef',
    category: '肉类',
    calories: 170,
    protein: 28.0,
    carbs: 0,
    fat: 5.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '猪肉',
    nameEn: 'Pork',
    category: '肉类',
    calories: 242,
    protein: 27.0,
    carbs: 0,
    fat: 14.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '三文鱼',
    nameEn: 'Salmon',
    category: '肉类',
    calories: 208,
    protein: 20.0,
    carbs: 0,
    fat: 13.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '虾',
    nameEn: 'Shrimp',
    category: '肉类',
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鲈鱼',
    nameEn: 'Sea Bass',
    category: '肉类',
    calories: 105,
    protein: 22.0,
    carbs: 0,
    fat: 1.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '排骨',
    nameEn: 'Pork Ribs',
    category: '肉类',
    calories: 278,
    protein: 18.0,
    carbs: 0.5,
    fat: 23.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '羊肉',
    nameEn: 'Lamb',
    category: '肉类',
    calories: 294,
    protein: 25.0,
    carbs: 0,
    fat: 21.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鸭肉',
    nameEn: 'Duck',
    category: '肉类',
    calories: 240,
    protein: 19.0,
    carbs: 0,
    fat: 18.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鲤鱼',
    nameEn: 'Carp',
    category: '肉类',
    calories: 109,
    protein: 20.0,
    carbs: 0,
    fat: 2.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '带鱼',
    nameEn: 'Hairtail',
    category: '肉类',
    calories: 127,
    protein: 20.0,
    carbs: 0,
    fat: 4.9,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鱿鱼',
    nameEn: 'Squid',
    category: '肉类',
    calories: 92,
    protein: 18.0,
    carbs: 0.5,
    fat: 1.2,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '牛蛙',
    nameEn: 'Bullfrog',
    category: '肉类',
    calories: 81,
    protein: 18.0,
    carbs: 0,
    fat: 0.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '肥牛',
    nameEn: 'Fatty Beef',
    category: '肉类',
    calories: 310,
    protein: 18.0,
    carbs: 0,
    fat: 27.0,
    fiber: 0,
    servingSize: 100,
  },

  // ==================== 蛋类 ====================
  {
    name: '鸡蛋',
    nameEn: 'Egg',
    category: '蛋类',
    calories: 144,
    protein: 13.0,
    carbs: 1.1,
    fat: 9.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '蛋白',
    nameEn: 'Egg White',
    category: '蛋类',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鸭蛋',
    nameEn: 'Duck Egg',
    category: '蛋类',
    calories: 180,
    protein: 12.6,
    carbs: 0.7,
    fat: 13.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '咸鸭蛋',
    nameEn: 'Salted Duck Egg',
    category: '蛋类',
    calories: 190,
    protein: 12.7,
    carbs: 4.7,
    fat: 12.7,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '皮蛋',
    nameEn: 'Century Egg',
    category: '蛋类',
    calories: 171,
    protein: 14.2,
    carbs: 4.5,
    fat: 10.7,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鹌鹑蛋',
    nameEn: 'Quail Egg',
    category: '蛋类',
    calories: 160,
    protein: 12.8,
    carbs: 2.1,
    fat: 11.1,
    fiber: 0,
    servingSize: 100,
  },

  // ==================== 蔬菜类 ====================
  {
    name: '西兰花',
    nameEn: 'Broccoli',
    category: '蔬菜',
    calories: 34,
    protein: 2.8,
    carbs: 7.0,
    fat: 0.4,
    fiber: 2.6,
    servingSize: 100,
  },
  {
    name: '菠菜',
    nameEn: 'Spinach',
    category: '蔬菜',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: 100,
  },
  {
    name: '番茄',
    nameEn: 'Tomato',
    category: '蔬菜',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '黄瓜',
    nameEn: 'Cucumber',
    category: '蔬菜',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '胡萝卜',
    nameEn: 'Carrot',
    category: '蔬菜',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    servingSize: 100,
  },
  {
    name: '白菜',
    nameEn: 'Chinese Cabbage',
    category: '蔬菜',
    calories: 13,
    protein: 1.2,
    carbs: 2.4,
    fat: 0.2,
    fiber: 0.9,
    servingSize: 100,
  },
  {
    name: '生菜',
    nameEn: 'Lettuce',
    category: '蔬菜',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    servingSize: 100,
  },
  {
    name: '青椒',
    nameEn: 'Green Pepper',
    category: '蔬菜',
    calories: 22,
    protein: 1.0,
    carbs: 5.3,
    fat: 0.2,
    fiber: 1.7,
    servingSize: 100,
  },
  {
    name: '茄子',
    nameEn: 'Eggplant',
    category: '蔬菜',
    calories: 25,
    protein: 1.0,
    carbs: 6.0,
    fat: 0.2,
    fiber: 3.0,
    servingSize: 100,
  },
  {
    name: '冬瓜',
    nameEn: 'Winter Melon',
    category: '蔬菜',
    calories: 11,
    protein: 0.4,
    carbs: 2.6,
    fat: 0.2,
    fiber: 0.7,
    servingSize: 100,
  },
  {
    name: '南瓜',
    nameEn: 'Pumpkin',
    category: '蔬菜',
    calories: 26,
    protein: 1.0,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '苦瓜',
    nameEn: 'Bitter Melon',
    category: '蔬菜',
    calories: 19,
    protein: 1.0,
    carbs: 4.3,
    fat: 0.1,
    fiber: 1.4,
    servingSize: 100,
  },
  {
    name: '芹菜',
    nameEn: 'Celery',
    category: '蔬菜',
    calories: 14,
    protein: 0.7,
    carbs: 3.0,
    fat: 0.2,
    fiber: 1.6,
    servingSize: 100,
  },
  {
    name: '韭菜',
    nameEn: 'Chinese Chives',
    category: '蔬菜',
    calories: 26,
    protein: 2.4,
    carbs: 4.6,
    fat: 0.4,
    fiber: 1.4,
    servingSize: 100,
  },
  {
    name: '豆角',
    nameEn: 'Green Bean',
    category: '蔬菜',
    calories: 31,
    protein: 1.8,
    carbs: 7.0,
    fat: 0.1,
    fiber: 2.7,
    servingSize: 100,
  },
  {
    name: '莲藕',
    nameEn: 'Lotus Root',
    category: '蔬菜',
    calories: 73,
    protein: 2.0,
    carbs: 16.4,
    fat: 0.2,
    fiber: 2.2,
    servingSize: 100,
  },
  {
    name: '蘑菇',
    nameEn: 'Mushroom',
    category: '蔬菜',
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1.0,
    servingSize: 100,
  },
  {
    name: '金针菇',
    nameEn: 'Enoki Mushroom',
    category: '蔬菜',
    calories: 32,
    protein: 2.8,
    carbs: 6.0,
    fat: 0.2,
    fiber: 2.3,
    servingSize: 100,
  },
  {
    name: '木耳',
    nameEn: 'Wood Ear',
    category: '蔬菜',
    calories: 27,
    protein: 1.5,
    carbs: 6.0,
    fat: 0.2,
    fiber: 2.6,
    servingSize: 100,
  },
  {
    name: '海带',
    nameEn: 'Kelp',
    category: '蔬菜',
    calories: 12,
    protein: 1.2,
    carbs: 2.1,
    fat: 0.1,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '紫菜',
    nameEn: 'Seaweed',
    category: '蔬菜',
    calories: 35,
    protein: 5.4,
    carbs: 5.2,
    fat: 0.2,
    fiber: 2.1,
    servingSize: 100,
  },

  // ==================== 水果类 ====================
  {
    name: '苹果',
    nameEn: 'Apple',
    category: '水果',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '香蕉',
    nameEn: 'Banana',
    category: '水果',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    servingSize: 100,
  },
  {
    name: '橙子',
    nameEn: 'Orange',
    category: '水果',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '葡萄',
    nameEn: 'Grape',
    category: '水果',
    calories: 69,
    protein: 0.7,
    carbs: 17.2,
    fat: 0.2,
    fiber: 0.9,
    servingSize: 100,
  },
  {
    name: '草莓',
    nameEn: 'Strawberry',
    category: '水果',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '蓝莓',
    nameEn: 'Blueberry',
    category: '水果',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '西瓜',
    nameEn: 'Watermelon',
    category: '水果',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    servingSize: 100,
  },
  {
    name: '牛油果',
    nameEn: 'Avocado',
    category: '水果',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    servingSize: 100,
  },
  {
    name: '梨',
    nameEn: 'Pear',
    category: '水果',
    calories: 42,
    protein: 0.4,
    carbs: 10.9,
    fat: 0.1,
    fiber: 2.1,
    servingSize: 100,
  },
  {
    name: '桃子',
    nameEn: 'Peach',
    category: '水果',
    calories: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.2,
    fiber: 1.5,
    servingSize: 100,
  },
  {
    name: '猕猴桃',
    nameEn: 'Kiwi',
    category: '水果',
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3.0,
    servingSize: 100,
  },
  {
    name: '芒果',
    nameEn: 'Mango',
    category: '水果',
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    fiber: 1.6,
    servingSize: 100,
  },
  {
    name: '菠萝',
    nameEn: 'Pineapple',
    category: '水果',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    servingSize: 100,
  },
  {
    name: '荔枝',
    nameEn: 'Lychee',
    category: '水果',
    calories: 66,
    protein: 0.8,
    carbs: 16.5,
    fat: 0.1,
    fiber: 1.3,
    servingSize: 100,
  },
  {
    name: '龙眼',
    nameEn: 'Longan',
    category: '水果',
    calories: 71,
    protein: 1.2,
    carbs: 16.3,
    fat: 0.1,
    fiber: 0.4,
    servingSize: 100,
  },
  {
    name: '榴莲',
    nameEn: 'Durian',
    category: '水果',
    calories: 147,
    protein: 2.0,
    carbs: 27.1,
    fat: 5.3,
    fiber: 3.8,
    servingSize: 100,
  },
  {
    name: '樱桃',
    nameEn: 'Cherry',
    category: '水果',
    calories: 50,
    protein: 1.0,
    carbs: 12.0,
    fat: 0.2,
    fiber: 1.6,
    servingSize: 100,
  },
  {
    name: '柚子',
    nameEn: 'Pomelo',
    category: '水果',
    calories: 38,
    protein: 0.8,
    carbs: 9.6,
    fat: 0.0,
    fiber: 1.0,
    servingSize: 100,
  },
  {
    name: '火龙果',
    nameEn: 'Dragon Fruit',
    category: '水果',
    calories: 51,
    protein: 1.1,
    carbs: 13.3,
    fat: 0.2,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '哈密瓜',
    nameEn: 'Cantaloupe',
    category: '水果',
    calories: 34,
    protein: 0.8,
    carbs: 8.0,
    fat: 0.1,
    fiber: 0.9,
    servingSize: 100,
  },

  // ==================== 乳制品 ====================
  {
    name: '牛奶',
    nameEn: 'Milk',
    category: '乳制品',
    calories: 54,
    protein: 3.0,
    carbs: 5.0,
    fat: 3.2,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '酸奶',
    nameEn: 'Yogurt',
    category: '乳制品',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '低脂酸奶',
    nameEn: 'Low-fat Yogurt',
    category: '乳制品',
    calories: 47,
    protein: 4.0,
    carbs: 5.0,
    fat: 1.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '奶酪',
    nameEn: 'Cheese',
    category: '乳制品',
    calories: 402,
    protein: 25.0,
    carbs: 1.3,
    fat: 33.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '脱脂牛奶',
    nameEn: 'Skim Milk',
    category: '乳制品',
    calories: 35,
    protein: 3.4,
    carbs: 5.0,
    fat: 0.1,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '全脂奶粉',
    nameEn: 'Whole Milk Powder',
    category: '乳制品',
    calories: 478,
    protein: 20.1,
    carbs: 51.7,
    fat: 21.0,
    fiber: 0,
    servingSize: 100,
  },

  // ==================== 豆制品 ====================
  {
    name: '豆腐',
    nameEn: 'Tofu',
    category: '豆制品',
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fat: 4.2,
    fiber: 0.3,
    servingSize: 100,
  },
  {
    name: '豆浆',
    nameEn: 'Soy Milk',
    category: '豆制品',
    calories: 33,
    protein: 2.9,
    carbs: 1.8,
    fat: 1.9,
    fiber: 0.6,
    servingSize: 100,
  },
  {
    name: '黄豆',
    nameEn: 'Soybean',
    category: '豆制品',
    calories: 359,
    protein: 35.0,
    carbs: 20.0,
    fat: 16.0,
    fiber: 15.5,
    servingSize: 100,
  },
  {
    name: '豆皮',
    nameEn: 'Tofu Skin',
    category: '豆制品',
    calories: 409,
    protein: 44.6,
    carbs: 18.8,
    fat: 17.4,
    fiber: 0.2,
    servingSize: 100,
  },
  {
    name: '腐竹',
    nameEn: 'Dried Tofu Skin',
    category: '豆制品',
    calories: 459,
    protein: 44.6,
    carbs: 22.3,
    fat: 21.7,
    fiber: 1.0,
    servingSize: 100,
  },
  {
    name: '红豆',
    nameEn: 'Red Bean',
    category: '豆制品',
    calories: 324,
    protein: 20.2,
    carbs: 63.4,
    fat: 0.6,
    fiber: 7.7,
    servingSize: 100,
  },
  {
    name: '绿豆',
    nameEn: 'Mung Bean',
    category: '豆制品',
    calories: 316,
    protein: 21.6,
    carbs: 62.0,
    fat: 0.8,
    fiber: 6.4,
    servingSize: 100,
  },
  {
    name: '黑豆',
    nameEn: 'Black Bean',
    category: '豆制品',
    calories: 381,
    protein: 36.0,
    carbs: 33.6,
    fat: 15.9,
    fiber: 10.2,
    servingSize: 100,
  },

  // ==================== 坚果类 ====================
  {
    name: '杏仁',
    nameEn: 'Almond',
    category: '坚果',
    calories: 579,
    protein: 21.0,
    carbs: 22.0,
    fat: 50.0,
    fiber: 12.5,
    servingSize: 100,
  },
  {
    name: '核桃',
    nameEn: 'Walnut',
    category: '坚果',
    calories: 654,
    protein: 15.0,
    carbs: 14.0,
    fat: 65.0,
    fiber: 6.7,
    servingSize: 100,
  },
  {
    name: '花生',
    nameEn: 'Peanut',
    category: '坚果',
    calories: 567,
    protein: 25.0,
    carbs: 16.0,
    fat: 49.0,
    fiber: 8.5,
    servingSize: 100,
  },
  {
    name: '腰果',
    nameEn: 'Cashew',
    category: '坚果',
    calories: 552,
    protein: 18.0,
    carbs: 30.0,
    fat: 44.0,
    fiber: 3.3,
    servingSize: 100,
  },
  {
    name: '开心果',
    nameEn: 'Pistachio',
    category: '坚果',
    calories: 562,
    protein: 20.0,
    carbs: 28.0,
    fat: 45.0,
    fiber: 10.3,
    servingSize: 100,
  },
  {
    name: '瓜子',
    nameEn: 'Sunflower Seeds',
    category: '坚果',
    calories: 606,
    protein: 23.0,
    carbs: 20.0,
    fat: 53.0,
    fiber: 8.6,
    servingSize: 100,
  },

  // ==================== 饮品 ====================
  {
    name: '咖啡（黑）',
    nameEn: 'Black Coffee',
    category: '饮品',
    calories: 2,
    protein: 0.3,
    carbs: 0.2,
    fat: 0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '绿茶',
    nameEn: 'Green Tea',
    category: '饮品',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '橙汁',
    nameEn: 'Orange Juice',
    category: '饮品',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    servingSize: 100,
  },
  {
    name: '可乐',
    nameEn: 'Cola',
    category: '饮品',
    calories: 43,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '奶茶',
    nameEn: 'Milk Tea',
    category: '饮品',
    calories: 62,
    protein: 1.2,
    carbs: 12.0,
    fat: 1.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '豆浆（甜）',
    nameEn: 'Sweet Soy Milk',
    category: '饮品',
    calories: 48,
    protein: 2.5,
    carbs: 6.5,
    fat: 1.8,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '椰汁',
    nameEn: 'Coconut Milk',
    category: '饮品',
    calories: 51,
    protein: 0.7,
    carbs: 6.3,
    fat: 2.3,
    fiber: 0,
    servingSize: 100,
  },

  // ==================== 油脂类 ====================
  {
    name: '橄榄油',
    nameEn: 'Olive Oil',
    category: '油脂',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '花生油',
    nameEn: 'Peanut Oil',
    category: '油脂',
    calories: 899,
    protein: 0,
    carbs: 0,
    fat: 99.9,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '黄油',
    nameEn: 'Butter',
    category: '油脂',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '猪油',
    nameEn: 'Lard',
    category: '油脂',
    calories: 902,
    protein: 0.2,
    carbs: 0,
    fat: 99.6,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '芝麻油',
    nameEn: 'Sesame Oil',
    category: '油脂',
    calories: 898,
    protein: 0,
    carbs: 0,
    fat: 99.8,
    fiber: 0,
    servingSize: 100,
  },

  // ==================== 中式菜品 ====================
  {
    name: '红烧肉',
    nameEn: 'Braised Pork Belly',
    category: '中式菜品',
    calories: 358,
    protein: 12.0,
    carbs: 8.5,
    fat: 32.0,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '宫保鸡丁',
    nameEn: 'Kung Pao Chicken',
    category: '中式菜品',
    calories: 195,
    protein: 15.0,
    carbs: 8.0,
    fat: 11.0,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '鱼香肉丝',
    nameEn: 'Fish-Flavored Shredded Pork',
    category: '中式菜品',
    calories: 168,
    protein: 10.0,
    carbs: 12.0,
    fat: 9.0,
    fiber: 1.5,
    servingSize: 100,
  },
  {
    name: '麻婆豆腐',
    nameEn: 'Mapo Tofu',
    category: '中式菜品',
    calories: 128,
    protein: 8.0,
    carbs: 6.0,
    fat: 8.0,
    fiber: 0.8,
    servingSize: 100,
  },
  {
    name: '糖醋排骨',
    nameEn: 'Sweet and Sour Ribs',
    category: '中式菜品',
    calories: 298,
    protein: 14.0,
    carbs: 18.0,
    fat: 19.0,
    fiber: 0.3,
    servingSize: 100,
  },
  {
    name: '回锅肉',
    nameEn: 'Twice-Cooked Pork',
    category: '中式菜品',
    calories: 285,
    protein: 12.0,
    carbs: 6.0,
    fat: 24.0,
    fiber: 0.8,
    servingSize: 100,
  },
  {
    name: '清蒸鱼',
    nameEn: 'Steamed Fish',
    category: '中式菜品',
    calories: 112,
    protein: 20.0,
    carbs: 2.0,
    fat: 3.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '番茄炒蛋',
    nameEn: 'Tomato Scrambled Eggs',
    category: '中式菜品',
    calories: 147,
    protein: 9.0,
    carbs: 5.0,
    fat: 10.0,
    fiber: 0.8,
    servingSize: 100,
  },
  {
    name: '青椒肉丝',
    nameEn: 'Stir-fried Pork with Green Pepper',
    category: '中式菜品',
    calories: 165,
    protein: 12.0,
    carbs: 6.0,
    fat: 11.0,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '酸菜鱼',
    nameEn: 'Fish with Pickled Cabbage',
    category: '中式菜品',
    calories: 118,
    protein: 18.0,
    carbs: 4.0,
    fat: 4.0,
    fiber: 0.6,
    servingSize: 100,
  },
  {
    name: '水煮牛肉',
    nameEn: 'Boiled Beef',
    category: '中式菜品',
    calories: 198,
    protein: 18.0,
    carbs: 5.0,
    fat: 12.0,
    fiber: 1.0,
    servingSize: 100,
  },
  {
    name: '蒜蓉西兰花',
    nameEn: 'Garlic Broccoli',
    category: '中式菜品',
    calories: 58,
    protein: 3.0,
    carbs: 6.0,
    fat: 3.0,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '地三鲜',
    nameEn: 'Di San Xian',
    category: '中式菜品',
    calories: 135,
    protein: 3.0,
    carbs: 15.0,
    fat: 7.0,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '红烧茄子',
    nameEn: 'Braised Eggplant',
    category: '中式菜品',
    calories: 88,
    protein: 1.5,
    carbs: 10.0,
    fat: 5.0,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '干煸豆角',
    nameEn: 'Dry-Fried Green Beans',
    category: '中式菜品',
    calories: 112,
    protein: 3.0,
    carbs: 8.0,
    fat: 8.0,
    fiber: 2.5,
    servingSize: 100,
  },

  // ==================== 快餐类 ====================
  {
    name: '汉堡包',
    nameEn: 'Hamburger',
    category: '快餐',
    calories: 295,
    protein: 17.0,
    carbs: 24.0,
    fat: 13.8,
    fiber: 1.3,
    servingSize: 100,
  },
  {
    name: '薯条',
    nameEn: 'French Fries',
    category: '快餐',
    calories: 312,
    protein: 3.4,
    carbs: 38.0,
    fat: 16.0,
    fiber: 3.8,
    servingSize: 100,
  },
  {
    name: '披萨',
    nameEn: 'Pizza',
    category: '快餐',
    calories: 266,
    protein: 11.0,
    carbs: 33.0,
    fat: 10.0,
    fiber: 2.3,
    servingSize: 100,
  },
  {
    name: '炸鸡',
    nameEn: 'Fried Chicken',
    category: '快餐',
    calories: 298,
    protein: 18.0,
    carbs: 12.0,
    fat: 20.0,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '热狗',
    nameEn: 'Hot Dog',
    category: '快餐',
    calories: 290,
    protein: 10.0,
    carbs: 24.0,
    fat: 17.0,
    fiber: 0.8,
    servingSize: 100,
  },

  // ==================== 零食类 ====================
  {
    name: '薯片',
    nameEn: 'Potato Chips',
    category: '零食',
    calories: 536,
    protein: 7.0,
    carbs: 52.0,
    fat: 35.0,
    fiber: 4.4,
    servingSize: 100,
  },
  {
    name: '巧克力',
    nameEn: 'Chocolate',
    category: '零食',
    calories: 546,
    protein: 5.0,
    carbs: 59.0,
    fat: 31.0,
    fiber: 3.4,
    servingSize: 100,
  },
  {
    name: '饼干',
    nameEn: 'Biscuit',
    category: '零食',
    calories: 433,
    protein: 6.0,
    carbs: 72.0,
    fat: 15.0,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '蛋糕',
    nameEn: 'Cake',
    category: '零食',
    calories: 348,
    protein: 5.0,
    carbs: 52.0,
    fat: 14.0,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '冰淇淋',
    nameEn: 'Ice Cream',
    category: '零食',
    calories: 207,
    protein: 3.5,
    carbs: 24.0,
    fat: 11.0,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '爆米花',
    nameEn: 'Popcorn',
    category: '零食',
    calories: 387,
    protein: 13.0,
    carbs: 78.0,
    fat: 4.5,
    fiber: 9.0,
    servingSize: 100,
  },
];
