/**
 * 食物数据库种子数据
 * 包含常见食物的营养成分信息
 */

export const seedFoods = [
  // 主食类
  {
    name: '米饭',
    nameEn: 'Steamed Rice',
    category: '主食',
    calories: 116,
    protein: 2.6,
    carbs: 25.9,
    fat: 0.3,
    fiber: 0.3,
    servingSize: 100,
  },
  {
    name: '糙米饭',
    nameEn: 'Brown Rice',
    category: '主食',
    calories: 111,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    fiber: 1.8,
    servingSize: 100,
  },
  {
    name: '面条',
    nameEn: 'Noodles',
    category: '主食',
    calories: 138,
    protein: 4.5,
    carbs: 28.1,
    fat: 0.8,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '全麦面包',
    nameEn: 'Whole Wheat Bread',
    category: '主食',
    calories: 247,
    protein: 9.5,
    carbs: 46.4,
    fat: 2.8,
    fiber: 6.0,
    servingSize: 100,
  },
  {
    name: '燕麦',
    nameEn: 'Oatmeal',
    category: '主食',
    calories: 367,
    protein: 13.2,
    carbs: 66.3,
    fat: 6.7,
    fiber: 10.3,
    servingSize: 100,
  },
  {
    name: '红薯',
    nameEn: 'Sweet Potato',
    category: '主食',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 2.5,
    servingSize: 100,
  },
  {
    name: '土豆',
    nameEn: 'Potato',
    category: '主食',
    calories: 77,
    protein: 2.0,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    servingSize: 100,
  },

  // 肉类
  {
    name: '鸡胸肉',
    nameEn: 'Chicken Breast',
    category: '肉类',
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鸡腿肉',
    nameEn: 'Chicken Thigh',
    category: '肉类',
    calories: 209,
    protein: 26.0,
    carbs: 0,
    fat: 11.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '牛肉',
    nameEn: 'Beef',
    category: '肉类',
    calories: 250,
    protein: 26.0,
    carbs: 0,
    fat: 15.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '瘦牛肉',
    nameEn: 'Lean Beef',
    category: '肉类',
    calories: 170,
    protein: 28.0,
    carbs: 0,
    fat: 5.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '猪肉',
    nameEn: 'Pork',
    category: '肉类',
    calories: 242,
    protein: 27.0,
    carbs: 0,
    fat: 14.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '三文鱼',
    nameEn: 'Salmon',
    category: '肉类',
    calories: 208,
    protein: 20.0,
    carbs: 0,
    fat: 13.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '虾',
    nameEn: 'Shrimp',
    category: '肉类',
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鲈鱼',
    nameEn: 'Sea Bass',
    category: '肉类',
    calories: 105,
    protein: 22.0,
    carbs: 0,
    fat: 1.5,
    fiber: 0,
    servingSize: 100,
  },

  // 蛋类
  {
    name: '鸡蛋',
    nameEn: 'Egg',
    category: '蛋类',
    calories: 144,
    protein: 13.0,
    carbs: 1.1,
    fat: 9.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '蛋白',
    nameEn: 'Egg White',
    category: '蛋类',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '鸭蛋',
    nameEn: 'Duck Egg',
    category: '蛋类',
    calories: 180,
    protein: 12.6,
    carbs: 0.7,
    fat: 13.0,
    fiber: 0,
    servingSize: 100,
  },

  // 蔬菜类
  {
    name: '西兰花',
    nameEn: 'Broccoli',
    category: '蔬菜',
    calories: 34,
    protein: 2.8,
    carbs: 7.0,
    fat: 0.4,
    fiber: 2.6,
    servingSize: 100,
  },
  {
    name: '菠菜',
    nameEn: 'Spinach',
    category: '蔬菜',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: 100,
  },
  {
    name: '番茄',
    nameEn: 'Tomato',
    category: '蔬菜',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    servingSize: 100,
  },
  {
    name: '黄瓜',
    nameEn: 'Cucumber',
    category: '蔬菜',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    servingSize: 100,
  },
  {
    name: '胡萝卜',
    nameEn: 'Carrot',
    category: '蔬菜',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    servingSize: 100,
  },
  {
    name: '白菜',
    nameEn: 'Chinese Cabbage',
    category: '蔬菜',
    calories: 13,
    protein: 1.2,
    carbs: 2.4,
    fat: 0.2,
    fiber: 0.9,
    servingSize: 100,
  },
  {
    name: '生菜',
    nameEn: 'Lettuce',
    category: '蔬菜',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    servingSize: 100,
  },
  {
    name: '青椒',
    nameEn: 'Green Pepper',
    category: '蔬菜',
    calories: 22,
    protein: 1.0,
    carbs: 5.3,
    fat: 0.2,
    fiber: 1.7,
    servingSize: 100,
  },

  // 水果类
  {
    name: '苹果',
    nameEn: 'Apple',
    category: '水果',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '香蕉',
    nameEn: 'Banana',
    category: '水果',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    servingSize: 100,
  },
  {
    name: '橙子',
    nameEn: 'Orange',
    category: '水果',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '葡萄',
    nameEn: 'Grape',
    category: '水果',
    calories: 69,
    protein: 0.7,
    carbs: 17.2,
    fat: 0.2,
    fiber: 0.9,
    servingSize: 100,
  },
  {
    name: '草莓',
    nameEn: 'Strawberry',
    category: '水果',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    servingSize: 100,
  },
  {
    name: '蓝莓',
    nameEn: 'Blueberry',
    category: '水果',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    servingSize: 100,
  },
  {
    name: '西瓜',
    nameEn: 'Watermelon',
    category: '水果',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    servingSize: 100,
  },
  {
    name: '牛油果',
    nameEn: 'Avocado',
    category: '水果',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    servingSize: 100,
  },

  // 乳制品
  {
    name: '牛奶',
    nameEn: 'Milk',
    category: '乳制品',
    calories: 54,
    protein: 3.0,
    carbs: 5.0,
    fat: 3.2,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '酸奶',
    nameEn: 'Yogurt',
    category: '乳制品',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '低脂酸奶',
    nameEn: 'Low-fat Yogurt',
    category: '乳制品',
    calories: 47,
    protein: 4.0,
    carbs: 5.0,
    fat: 1.5,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '奶酪',
    nameEn: 'Cheese',
    category: '乳制品',
    calories: 402,
    protein: 25.0,
    carbs: 1.3,
    fat: 33.0,
    fiber: 0,
    servingSize: 100,
  },

  // 豆制品
  {
    name: '豆腐',
    nameEn: 'Tofu',
    category: '豆制品',
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fat: 4.2,
    fiber: 0.3,
    servingSize: 100,
  },
  {
    name: '豆浆',
    nameEn: 'Soy Milk',
    category: '豆制品',
    calories: 33,
    protein: 2.9,
    carbs: 1.8,
    fat: 1.9,
    fiber: 0.6,
    servingSize: 100,
  },
  {
    name: '黄豆',
    nameEn: 'Soybean',
    category: '豆制品',
    calories: 359,
    protein: 35.0,
    carbs: 20.0,
    fat: 16.0,
    fiber: 15.5,
    servingSize: 100,
  },

  // 坚果类
  {
    name: '杏仁',
    nameEn: 'Almond',
    category: '坚果',
    calories: 579,
    protein: 21.0,
    carbs: 22.0,
    fat: 50.0,
    fiber: 12.5,
    servingSize: 100,
  },
  {
    name: '核桃',
    nameEn: 'Walnut',
    category: '坚果',
    calories: 654,
    protein: 15.0,
    carbs: 14.0,
    fat: 65.0,
    fiber: 6.7,
    servingSize: 100,
  },
  {
    name: '花生',
    nameEn: 'Peanut',
    category: '坚果',
    calories: 567,
    protein: 25.0,
    carbs: 16.0,
    fat: 49.0,
    fiber: 8.5,
    servingSize: 100,
  },

  // 饮品
  {
    name: '咖啡（黑）',
    nameEn: 'Black Coffee',
    category: '饮品',
    calories: 2,
    protein: 0.3,
    carbs: 0.2,
    fat: 0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '绿茶',
    nameEn: 'Green Tea',
    category: '饮品',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '橙汁',
    nameEn: 'Orange Juice',
    category: '饮品',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    servingSize: 100,
  },

  // 油脂类
  {
    name: '橄榄油',
    nameEn: 'Olive Oil',
    category: '油脂',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100.0,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '花生油',
    nameEn: 'Peanut Oil',
    category: '油脂',
    calories: 899,
    protein: 0,
    carbs: 0,
    fat: 99.9,
    fiber: 0,
    servingSize: 100,
  },
  {
    name: '黄油',
    nameEn: 'Butter',
    category: '油脂',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.0,
    fiber: 0,
    servingSize: 100,
  },
];
